name: CI/CD Pipeline

on:
  push:
    branches: [main, master]

jobs:
  build:
    name: Etapa de Build
    runs-on: ubuntu-latest

    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Validar compilaciÃ³n TypeScript
        run: npm run build

  docker:
    name: Etapa de Docker
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Login a ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}


      - name: Construir y subir imagen
        run: |
          IMAGE_TAG=practica5-cloud:${{ github.run_number }}
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG ${{ secrets.ECR_URI }}:$IMAGE_TAG
          docker push ${{ secrets.ECR_URI }}:$IMAGE_TAG

  deploy:
    name: Etapa de Deploy
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Desplegar en EC2
        run: |
          IMAGE_TAG=practica5-cloud:${{ github.run_number }}
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} << EOF
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}
            docker pull ${{ secrets.ECR_URI }}:$IMAGE_TAG
            docker stop practica5 || true
            docker rm practica5 || true
            docker run -d --name practica5 -p 80:3000 ${{ secrets.ECR_URI }}:$IMAGE_TAG
          EOF
